services:

  mysql:
    image: mysql:8.3.0
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Seoul
      MYSQL_DATABASE: newsseug
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - local-bridge

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - local-bridge

#  prometheus:
#    image: prom/prometheus:latest
#    container_name: prometheus
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - 9090:9090
#    networks:
#      - local-bridge
#
#  grafana:
#    image: grafana/grafana:latest
#    container_name: grafana
#    ports:
#      - 3000:3000
#    networks:
#      - local-bridge

networks:
  local-bridge:
    driver: bridge
